name: building, testing, linting
on: 
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
    
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Starting NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{matrix.node-version}}

      - name: Install node_modules
        run: npm install

      - name: Create production build
        run: npm run build:prod

      - name: Run unit tests
        run: npm run test:unit

      - name: Run screenshot tests
        run: | 
            npm storybook:build
            npx run test:ui:ci

      - name: Lint SCSS code
        run: npm run lint:scss:fix

      - name: Lint TypeScript code
        run: npm run lint:ts:fix


